### ISSUE TITLE
release a new version to PyPI

### ISSUE THREAD

**Issue by ktdreyer** [alfredodeza/helga-redmine#8]
Mind tagging and pushing a new release? This will contain support for `REDMINE_API_KEY` and reading private tickets.

**Comment by alfredodeza** [comment]
yes! sorry about the delay

**Comment by alfredodeza** [comment]
0.0.4 tagged and released https://pypi.python.org/pypi/helga-redmine

**Comment by ktdreyer** [comment]
awwww yeah :tada:
